# Generated by Django 5.2.15 on 2026-06-22 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                (
                    "service_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="businesses.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("reminder_24h_sent", "24h Reminder Sent"),
                            ("reminder_2h_sent", "2h Reminder Sent"),
                            ("reminder_failed", "Reminder Failed"),
                            ("reminder_opened", "Reminder Opened"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                            ("risk_calculated", "Risk Calculated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("actor_type", models.CharField(default="system", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["business", "scheduled_at"], name="appt_business_scheduled_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["business", "status", "scheduled_at"],
                name="appt_business_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentevent",
            index=models.Index(
                fields=["appointment", "created_at"],
                name="event_appointment_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentevent",
            index=models.Index(
                fields=["event_type", "created_at"], name="event_type_created_idx"
            ),
        ),
    ]
